import axios from 'axios';


export const FETCHING_CLASSES_START = "FETCHING_CLASSES_START";
export const FETCHING_CLASSES_SUCCESS = "FETCHING_CLASSES_SUCCESS";
export const FETCHING_CLASSES_FAILURE = "FETCHING_CLASSES_FAILURE";
export const TOGGLE_EDITING = "TOGGLE_EDITING";
export const ADD_CLASS = "ADD_CLASS";
export const DELETE_CLASS = "DELETE_CLASS";
export const UPDATE_CLASS = "UPDATE_CLASS";